all:
	@echo "FAIL!"
	@echo "Only possibility is 'install', which installs the script to /usr/local/sbin"
	@echo "and the config file to /etc/default. If the config file exists, it's not"
	@echo "touched. If the script exists, it's backed up to something first."

install:
	./do-install.sh
