---
- name: install-zbx-smartctl
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
  - name: "Install smartmontools"
    package:
      name: smartmontools
      state: latest
  - name: "Copy sudoers file"
    copy:
      src: ../sudoers_zabbix_smartctl
      dest: /etc/sudoers.d/sudoers_zabbix_smartctl
      validate: "visudo -cf %s"
      mode: 0440
  - name: "Copy agent config"
    copy:
      src: ../zabbix_smartctl.conf
      dest: /etc/zabbix/zabbix_agentd.d/zabbix_smartctl.conf
  - name: "Create scripts directory"
    file: 
      path: /etc/zabbix/scripts
      state: directory
  - name: "Copy script"
    copy:
      src: ../discovery-scripts/nix/smartctl-disks-discovery.pl
      dest: /etc/zabbix/scripts/smartctl-disks-discovery.pl
  - name: "Ensure script is executable"
    file: dest=/etc/zabbix/scripts/smartctl-disks-discovery.pl mode=a+x
  - name: "Restart zabbix-agent via systemd"
    systemd:
      name: zabbix-agent
      state: restarted
