all:
	@echo "Only valid target is 'install'"

install:
	@echo "not finished"
#install mqtt_to_pg_config.py mqtt_to_pg.py /usr/local/bin

# mqtt_to_pg_config.py
# mqtt_to_pg.ini
# mqtt_to_pg.py
# mqtt_to_pg.service
# __pycache__
