#pragma once

const int VRT_VERSION_1  =  1;	// Original version
const int VRT_VERSION_2  =  2;	// Added ability to show IC pin numbers
const int VRT_VERSION_3  =  3;	// Added ground fill parameters
const int VRT_VERSION_4  =  4;	// Simplified mapping of pinChar to pinIndex
const int VRT_VERSION_5  =  5;	// Added flag to show grid
const int VRT_VERSION_6  =  6;	// Added color saturation
const int VRT_VERSION_7  =  7;	// Added pin labels
const int VRT_VERSION_8  =  8;	// Added crystal component type
const int VRT_VERSION_9  =  9;	// Added more trimmers/relays/switches
const int VRT_VERSION_10 = 10;	// Added rectangles
const int VRT_VERSION_11 = 11;	// Added component manager, bounding rects, reworked Footprint class
const int VRT_VERSION_12 = 12;	// Added horizontal vero strips
const int VRT_VERSION_13 = 13;	// Added crop margin
const int VRT_VERSION_14 = 14;	// Added text manager
const int VRT_VERSION_15 = 15;	// Added text color
const int VRT_VERSION_16 = 16;	// Added more components
const int VRT_VERSION_17 = 17;	// Added text sizes for components and pins
const int VRT_VERSION_18 = 18;	// Added custom component type and shapes class
const int VRT_VERSION_19 = 19;	// Added component editor flag and new component attributes
const int VRT_VERSION_20 = 20;	// Added SURFACE_HOLE attribute
const int VRT_VERSION_21 = 21;	// Added target board size
const int VRT_VERSION_22 = 22;	// Label offsets measured in 1/16th of a square instead of 1/4
const int VRT_VERSION_23 = 23;	// Added component definer
const int VRT_VERSION_24 = 24;	// Added routing method parameter
const int VRT_VERSION_25 = 25;	// Moves some variables from CompElement to Element
const int VRT_VERSION_26 = 26;	// Reworked codes in Pin to allow 2 wires per grid point
const int VRT_VERSION_27 = 27;	// Modified Element to store additional wire info
const int VRT_VERSION_28 = 28;	// Added options for wires to share holes or cross/overlay
const int VRT_VERSION_29 = 29;	// Added color to component definition
const int VRT_VERSION_30 = 30;	// Added pin label alignment
const int VRT_VERSION_31 = 31;	// New treatment of labels under part rotation and centering.
const int VRT_VERSION_32 = 32;	// Added size of solder mask and silk screen pen
const int VRT_VERSION_33 = 33;	// Added PCB track mode, board edge margin, PTH/NPTH option
const int VRT_VERSION_34 = 34;	// Added 3rd dimension to grid, and display layer
const int VRT_VERSION_35 = 35;	// Added via dimensions
const int VRT_VERSION_36 = 36;	// Added thin tracks style
const int VRT_VERSION_37 = 37;	// Added flag to enable/disable vias
const int VRT_VERSION_CURRENT = VRT_VERSION_37;
