#!/bin/bash
# vim:ts=4:sw=4:sts=4:et:ai:fdm=marker

INSIGHTS="insights-client-boot.service insights-client-results.path insights-client.timer"
MODE='nada'

die() {
    echo "$*" 1>&2 
    exit 1
}

MODE="$1"
for s in $INSIGHTS
do
    case "$MODE" in
        'enable')
            echo "Enabling $s"
            systemctl unmask $s
            systemctl enable $s
            ;;
        'disable')
            echo "Disabling $s"
            systemctl disable $s
            systemctl mask $s
            ;;
        *)
            die "Syntax: $0 [ enable | disable ]"
            ;;
    esac
done
