#!/bin/bash
# vim:ts=4:sw=4:sts=4:et:ai:fdm=marker
#
# Disable or enable RedHat Insights - by Roy Sigurd Karlsbakk <roy@karlsbakk.net>
# At the time of writing, 2023-08-02, written to disable the whole crap since it leads
# to very funny memory leaks not detectable anywhere.
#

INSIGHTS="insights-client-boot.service insights-client-results.path insights-client.timer"
MODE='nada'

die() {
    echo "$*" 1>&2 
    exit 1
}

MODE="$1"
for s in $INSIGHTS
do
    case "$MODE" in
        'enable')
            echo "Enabling $s"
            systemctl unmask $s
            systemctl enable $s
            ;;
        'disable')
            echo "Disabling $s"
            systemctl disable $s
            systemctl mask $s
            ;;
        *)
            die "Syntax: $0 [ enable | disable ]"
            ;;
    esac
done
